/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: dbb88e9cfc40a0ffdb18d62ecdc7a060)
interface __BaseEnv_Env {
	BROWSER: BrowserRun;
	MODEL: "gemini-2.5-flash";
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MODEL" | "GOOGLE_GENERATIVE_AI_API_KEY">> {}
}
