/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 60684f164f3621e3d4acbc40c33cb028)
interface __BaseEnv_Env {
	BROWSER: BrowserRun;
	MODEL: "gemini-2.5-flash";
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	ChatAgent: DurableObjectNamespace<import("./src/server/index").ChatAgent>;
	ArtifactStore: DurableObjectNamespace<import("./src/server/index").ArtifactStore>;
	NEWS_WORKFLOW: Workflow<Parameters<import("./src/server/index").NewsWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "ChatAgent" | "ArtifactStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MODEL" | "GOOGLE_GENERATIVE_AI_API_KEY">> {}
}
