/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 033bdf736409612e2197b898190dc427)
interface __BaseEnv_Env {
  AI: Ai;
  MODEL: "openai/gpt-5.6-luna";
  AI_GATEWAY_ID: "experiment";
  ThinkAgent: DurableObjectNamespace<import("./src/server/index").ThinkAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server/index");
    durableNamespaces: "ThinkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "MODEL" | "AI_GATEWAY_ID">
  > {}
}
